# Generated by Django 3.1.7 on 2021-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=16)),
                ('category', models.IntegerField()),
                ('stock_type', models.IntegerField()),
                ('color', models.IntegerField()),
                ('size', models.IntegerField()),
                ('movement', models.IntegerField()),
            ],
        ),
    ]
