# Generated by Django 3.1.7 on 2021-04-27 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210426_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='movement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 13, 5, 59, 238080, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='stock',
            name='movement_registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
